### model
model_name_or_path: meta-llama/Llama-3-8B-Instruct


### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all

### dataset
cutoff_len: 2048
dataset: msmarco_dpo
dataset_dir: ../data/
ddp_timeout: 180000000
template: llama3
max_samples: 120000
overwrite_cache: true
preprocessing_num_workers: 16


### train
per_device_train_batch_size: 4
fp16: true
gradient_accumulation_steps: 8
learning_rate: 5.0e-06
pref_beta: 0.1
pref_loss: sigmoid
lr_scheduler_type: cosine
num_train_epochs: 3.0
warmup_ratio: 0.1

### output
output_dir: ../saves/Meta-Llama-3-8B-Instruct/lora/dpo/msmarco_dpo/msmarco_dpo
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500

### preference weights
weight_alpha: 2.0
