### model
model_name_or_path: meta-llama/Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: msmarco_sft
template: llama3
cutoff_len: 2048
max_samples: 120000
overwrite_cache: true
preprocessing_num_workers: 16

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
# kl_loss: 10.0

### output
output_dir: ../saves/Meta-Llama-3-8B-Instruct/lora/sft/msmarco_sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500
